lanuage: python
matrix:
  include:
  - env: TARGET=py2
  - env: TARGET=py3
  - env: TARGET=pep8
  - env: TARGET=mypy
  allow_failures:
  - env: TARGET=pep8
  - env: TARGET=mypy
sudo: required
services:
 - docker
install:
 - true
script:
- docker build . -f .travis/${TARGET}.docker
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: FIU8/3mER+/IyngbN1B1p8sUj6IiWXhTp3XC0jy+oab4MvAKY5s5i9AASejfVBPcCjYgUKOrNM0lvkdnNtmWQMnuYpLAjNDtYLnHqoupJ1PRXOmkGGDj+4Ivgk/gbitduoyXWkbxafuwyQ/PX3XbIda2pgs28SUQmIaYVKbcAtg=
  on:
    tags: true
    repo: ska-sa/pyxis
